This contains some basics about numpy!

In [2]:
#Import numpy library

import numpy as np

## Create arrays

Create array from python lists or nested lists using `np.array()`

In [3]:
#1-D array
a = np.array([1, 2, 3, 4, 5, 6])

#2-D array
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


Accessing array's element through indexes. Indexes starts at 0.

In [6]:
print(a[0]) #should print the first list of the nested list

print(a[0][2]) #should print 3

[1 2 3 4]
3


Creating arrays filled with `zeros, ones, emmpty, arange, linspace`.
 - zeros fill with zeros
 - ones fill with ones
 - empty fill with random numbers and is more efficient
 - arange fill with numbers with a range
 - linspace fill with evenly spaced numbers: provide begining, end and number of elements

In [10]:
a= np.zeros(2)
print(a)

a= np.ones(2)
print(a)

a= np.empty(2)
print(a)

a= np.arange(4)
print(a)

a= np.linspace(0, 10, num=5)
print(a)

[0. 0.]
[1. 1.]
[1. 1.]
[0 1 2 3]
[ 0.   2.5  5.   7.5 10. ]


By default it's float but we can set the type `dtype` we want like `int64`.

In [11]:
a= np.zeros(2, dtype=np.int64)
print(a)

[0 0]


## Adding, removing, and sorting elements

This section covers `np.sort()`, `np.concatenate()`

In [13]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr = np.sort(arr)
print(arr)

[1 2 3 4 5 6 7 8]


In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concatenate((a, b))
print(c)

[1 2 3 4 5 6 7 8]


In [21]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
z = np.concatenate((x, y), axis=0)
print(x)
print(y)
print(z)

[[1 2]
 [3 4]]
[[5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [22]:
array_example = np.array([
[[0, 1, 2, 3],
[4, 5, 6, 7]],

[[0, 1, 2, 3],
[4, 5, 6, 7]],

[[0 ,1 ,2, 3],
[4, 5, 6, 7]]

])

In [24]:
#to find the dimension
array_example.ndim #3-D
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [25]:
#To find the total number of elements in the array
array_example.size

24

In [26]:
#to find the shape of your array
array_example.shape 

(3, 2, 4)

## Reshaping an array

Use `.reshape` or `np.reshape`. The latter helps specify few more options.

In [28]:
#Create an array
a = np.arange(6)
print(a)

#Reshaping this into 3 rows and 2 columns
b = a.reshape(3, 2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [34]:
#Reshape from matrx to vector
c = np.reshape(a, newshape=(1, 6), order='C') #newshape takes either an elemt or a tuple.
print(c)

[[0 1 2 3 4 5]]


## How to convert a 1D array into a 2D array (how to add a new axis to an array)¶

Use `np.newaxis` to increase the dimension, `np.expand_dims`

In [36]:
# let's start with this array
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

#row vector
row_vector = a[np.newaxis, :]
row_vector.shape

#column vector
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

You can also expand an array by inserting a new axis at a specified position with `np.expand_dims`.

In [42]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
print(a)

(6,)
[1 2 3 4 5 6]


In [43]:
#add an axis at position 1
b = np.expand_dims(a, axis=1)
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [44]:
#add an axis at position 0
c = np.expand_dims(a, axis=0)
print(c.shape)
print(c)

(1, 6)
[[1 2 3 4 5 6]]


## Indexing and slicing
Same ways you can slice Python lists

In [48]:
data = np.array([1, 2, 3])
print(data[0:2])
print(data[1:])
print(data[-2:])
print(data[:-2])

[1 2]
[2 3]
[2 3]
[1]


If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

For example, if you start with this array:

In [49]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
#Print values that are lower than 8
print(a[a < 8])

#Print values that are greater or equal to 5
five_up = (a >= 5)
print(five_up)
print(a[five_up])

#Select elements that are divisible by 2
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[1 2 3 4 5 6 7]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


Or you can select elements that satisfy two conditions using the `&` and `|` operators

In [59]:
five_up = (a > 5) | (a == 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


Print Indices

In [60]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In this example, a tuple of arrays was returned: one for each dimension. The first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.<br>

If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them. For example:

In [62]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


If the element you’re looking for doesn’t exist in the array, then the returned array of indices will be empty. For example:

In [63]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


## How to create an array from existing data¶

This section covers `slicing` and `indexing`, `np.vstack()`, `np.hstack()`, `np.hsplit()`, `.view()`, `copy()`.